### ISSUE TITLE
annotation tracks no longer displayed as rectangle

### ISSUE THREAD

**Issue by jvolkening** [igvteam/igv.js#1618]
In testing the latest tag v2.15.0 compared to the previous release 2.13.11, it seems the features for an annotation track are no longer shown as rectangles, but only as arrows. Screenshots of example region using v2.13.11:

![Screenshot_2023-03-24_21-17-06](https://user-images.githubusercontent.com/11667655/227681851-7c4523a9-80b9-44cd-8698-527a42f840dd.png)

Screenshot of roughly same region using v2.15.0:

![Screenshot_2023-03-24_21-19-38](https://user-images.githubusercontent.com/11667655/227681871-ef623fb2-228b-43ae-987f-bafdc8dc2e7f.png)

Note differences in bottom track, loaded from a BED file. Is this a bug or a feature? If feature, is there a setting to restore the previous behavior?

**Comment by jrobinso** [comment]
Could you provide an example bed file?  This is what I see

<img width="2055" alt="Screen Shot 2023-03-24 at 8 56 00 PM" src="https://user-images.githubusercontent.com/933148/227691762-37a7b709-7e5e-4bb8-8199-da7a30b10b77.png">

**Comment by jvolkening** [comment]
Thanks, I will try to put together a MWE tomorrow. Is the track in that screenshot from a GFF or BED? GFF-based tracks are still working fine for me.

**Comment by jrobinso** [comment]
Bed

**Comment by jrobinso** [comment]
Just the section of your BED file reflected in that screenshot should be enough to sort this out.

**Comment by jvolkening** [comment]
Here is a one-feature BED that displays the behavior for me:
```tsv
#gffTags
track name="Test" useScore=1 viewLimits=0:50 color=32,74,135 altColor=164,0,0
ctg_01	10000	11000	Transcript=ABC;Read counts=A:4 B:5	25	+	10000	11000	255,0,0	1	1000	0
```

and here is the corresponding track configuration (in YAML):
```yaml
test_track:
  url: data/test.bed.gz
  delimiter: "\t"
  type: annotation
  format: bed
  name: test track (min_reads 4)
  displayMode: SQUISHED
  nameField: Transcript
  useScore: true
  category: Test_Features
  autoHeight: true
  minHeight: 50
  maxHeight: 160
```

**V2.13.11:**
![Screenshot_2023-03-25_10-36-06](https://user-images.githubusercontent.com/11667655/227727676-fc62ab95-c8a0-40a2-8de2-a0beee6fcd29.png)

**v2.15.0:**
![Screenshot_2023-03-25_10-41-38](https://user-images.githubusercontent.com/11667655/227727687-87d76bc9-258f-4260-9484-c7334acff6d0.png)

Thanks.
